# Generated by Django 3.1.1 on 2020-09-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentID', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.IntegerField()),
                ('vetID', models.IntegerField()),
                ('availabilityID', models.IntegerField()),
                ('reason', models.CharField(max_length=100)),
                ('petDetails', models.CharField(max_length=100)),
                ('_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
