# Generated by Django 3.1.1 on 2020-09-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('contactNo', models.IntegerField(max_length=15)),
                ('petName', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
