# Generated by Django 3.1.1 on 2020-09-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petcareuser',
            name='contactNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petcareuser',
            name='petName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
